version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
      steps:
        - checkout

        # download and cache dependencies

        # run install module
        - run: npm install

        # run test
        - run: npm test
