version 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8
      steps:
        - checkout

        # download and cache dependencies

        # run install module
        - run: yarn install

        # run test
        - run: yarn test
